### ISSUE TITLE
Function variables on same line vs separate lines

### ISSUE THREAD

**Issue by embano1** [jdob/visitors-operator#3]
I know it's personal preference, but for readability (as I'm reading through the code and having to focus more) I'd put all arguments on the same line. Most controllers I've seen follow the same pattern.

https://github.com/jdob/visitors-operator/blob/53c2e1d98b5b218dd1a33f2fba8dc13588318b3f/pkg/controller/visitorsapp/visitorsapp_controller.go#L115

**Comment by jdob** [comment]
My original intention was that I'd put this code into the book, so I was concerned about making it too wide. But now that I didn't go that route, it is particularly annoying to look at this way :)

I'll update accordingly. I'm pretty new to Go, so I'm all for learning and sticking to the conventions. Thanks for the input.

**Comment by jdob** [comment]
Cleaned up:

https://github.com/jdob/visitors-operator/commit/5b18c79fe98bfca7f0214b6e1db9919b96dcfa6f
